### ISSUE TITLE
Investigate MiniShift

### ISSUE THREAD

**Issue by scollier** [dustymabe/summit-2017-container-lab#2]

**Comment by scollier** [comment]
https://developers.redhat.com/blog/2016/10/11/four-creative-ways-to-create-an-openshiftkubernetes-dev-environment/

@dustymabe @tchughesiv @whitel any other docs for minishift that you are aware of?

**Comment by dustymabe** [comment]
Did some investigation tonight. Here is how to get up and running with minishift. 


Latest instructions for cdk beta 3 at [link](https://developers.redhat.com/blog/2017/02/28/using-red-hat-container-development-kit-3-beta/)

Start with RHEL7 machine and install and start libvirt:

```
yum install -y libvirt qemu-kvm
systemctl start libvirtd
```

Go to developers.redhat.com/downloads and login

Go to https://developers.redhat.com/products/cdk/download/ and
download the 3.0 beta 64-bit Linux binary.

Copy to RHEL7 system and extract.

```
scp /home/dustymabe/Downloads/cdk-3.0.beta-minishift-linux-amd64 cloud-user@192.168.122.179:
ssh cloud-user@192.168.122.179
sudo su -
mv cdk-3.0.beta-minishift-linux-amd64 /usr/local/bin/minishift
chmod +x /usr/local/bin/minishift
```

Grab docker-machine:

```
curl -L https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-Linux-x86_64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine
```

Grab docker-machine-driver-kvm

```
curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.8.2/docker-machine-driver-kvm > /usr/local/bin/docker-machine-driver-kvm
chmod +x /usr/local/bin/docker-machine-driver-kvm
```

If running as normal user add rules so that user can interact with
libvirt:

```
sudo usermod -a -G libvirt cloud-user
newgrp libvirt
```

Setup cdk

```
minishift setup-cdk

```

Start cdk. Please note [this bug](https://github.com/minishift/minishift/issues/570)
if your password has special characters in it.
```
export MINISHIFT_USERNAME=<rhn-username>
export MINISHIFT_PASSWORD=<rhn-password>
minishift start
```

Alias oc

```
alias oc=~/.minishift/cache/oc/v3.4.1.2/oc
oc whoami
```

Can access web console at 
https://192.168.42.181:8443  --> IP address will be different

**Comment by tchughesiv** [comment]
Your notes work well for me @dustymabe ... some addt'l options.  If we wanted to configure MiniShift w/ more resources... here's what that might look like.  This could be necessary to speed up the cluster's performance... especially if we leverage it for builds/registry work.

```bash
minishift config set cpus 4
minishift config set memory 4096
minishift config view
minishift delete
minishift start
```

OR

```bash
minishift start --cpus 4 --memory 4096
```

**Comment by dustymabe** [comment]
we have investigated minishift and have come up with a plan for supporting it. once we get a patched version of minishift we hope that the "offline" case works fine.

I'm going to close this issue for now.
